# Generated by Django 5.2.15 on 2026-07-01 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_clientprofile_project_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directclientaccess',
            name='unique_direct_client_access',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='pool_reason',
            field=models.CharField(blank=True, choices=[('', 'Не перебуває в пулі'), ('self_registered', 'Нова самостійна реєстрація'), ('employee_deactivated', 'Повторне призначення'), ('access_removed', 'Потрібне повторне призначення')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='directclientaccess',
            name='revoke_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='directclientaccess',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directclientaccess',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_client_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='crm_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='crm_audit_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='crm_audit_actor_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='crm_audit_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='directclientaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('client', 'employee'), name='unique_active_direct_client_access'),
        ),
    ]
