# Generated by Django 5.2.15 on 2026-07-02 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_clientprofile_marketing_email_consent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailserverconfiguration',
            name='company_name',
            field=models.CharField(default='Multisoft Velari', max_length=255),
        ),
        migrations.CreateModel(
            name='ClientGroupCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(max_length=150)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Очікує рішення'), ('approved', 'Схвалено'), ('rejected', 'Відхилено'), ('expired', 'Автоматично відхилено')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creation_request', to='crm.clientgroup')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_client_group_creation_requests', to=settings.AUTH_USER_MODEL)),
                ('proposed_clients', models.ManyToManyField(blank=True, related_name='proposed_group_creation_requests', to='crm.clientprofile')),
                ('proposed_employees', models.ManyToManyField(blank=True, related_name='proposed_client_group_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_client_group_creation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientGroupAdditionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Очікує рішення'), ('approved', 'Схвалено'), ('rejected', 'Відхилено'), ('expired', 'Автоматично відхилено')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_addition_requests', to='crm.clientprofile')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_client_group_addition_requests', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addition_requests', to='crm.clientgroup')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_client_group_addition_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('client', 'group'), name='one_pending_client_group_addition')],
            },
        ),
    ]
